version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/database.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app 